# Generated by Django 4.1.7 on 2023-02-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zhihu", "0002_remove_question_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="update_time",
        ),
    ]
