# Generated by Django 4.1.7 on 2023-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhihu", "0003_remove_question_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="update_time",
            field=models.IntegerField(default=0),
        ),
    ]
