# Generated by Django 4.1.7 on 2023-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhihu", "0004_answer_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
